trigger:
- main

pool:
  -name: my_agent_pool

steps:
- task: DotNetCoreCLI@2
  displayName: "Compilacion"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/SandboxProf'
- task: DotNetCoreCLI@2
  displayName: "Despliegue"
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/SandboxProf'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'TallerAzureB'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    DeploymentTypeLinux: 'oneDeploy'